services:
  postgres:
    container_name: 'example.postgres'
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - PGDATA=/data/postgres
    ports:
      - "65432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U example" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s